[versions]
checker = "3.22.1"
junit = "5.8.2"
geantyref = "1.3.13"
paper = "1.19.2-R0.1-SNAPSHOT"

[libraries]
checker-qual = { module = "org.checkerframework:checker-qual", version.ref = "checker" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
geantyref = { module = "io.leangen.geantyref:geantyref", version.ref = "geantyref" }
paper =  { module = "io.papermc.paper:paper-api", version.ref = "paper" }

# Gradle
gradle-licenser = "gradle.plugin.com.hierynomus.gradle.plugins:license-gradle-plugin:0.16.1"

